### ISSUE TITLE
Unnecessary/ugly direct console.error on req.on("error"...)

### ISSUE THREAD

**Issue by SimonX200** [ZaralDev/native-request#6]
Hi,

Why is there the buildin plain console error log in the error handler? 

 	req.on('error', function (error) {
 		callback(error);
 		console.error(error);
 	});

In production it produces things like this:

Error: connect ETIMEDOUT a.b.c.d:xxx
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:131:17) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '......,
  port: ...
}

The callback is handling the error and is deciding what/if/how to report the error situation.

Please remove the console.error

**Comment by ZaralDev** [comment]
Hey, 
thanks for the issue.

You're right, i'll remove this log asap
